// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gb_active_service_api.Data.Contexts;

#nullable disable

namespace gb_active_service_api.Migrations
{
    [DbContext(typeof(ActivesDbContext))]
    [Migration("20230519175955_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gb_active_service_api.Models.Active", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<Guid>("DependencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DependencyId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("Actives", (string)null);
                });

            modelBuilder.Entity("gb_active_service_api.Models.Dependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.ToTable("Dependencies", (string)null);
                });

            modelBuilder.Entity("gb_active_service_api.Models.Responsible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("Responsibles", (string)null);
                });

            modelBuilder.Entity("gb_active_service_api.Models.Active", b =>
                {
                    b.HasOne("gb_active_service_api.Models.Dependency", "Dependency")
                        .WithMany("Actives")
                        .HasForeignKey("DependencyId")
                        .IsRequired();

                    b.HasOne("gb_active_service_api.Models.Responsible", "Responsible")
                        .WithMany("Actives")
                        .HasForeignKey("ResponsibleId")
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("gb_active_service_api.Models.Dependency", b =>
                {
                    b.Navigation("Actives");
                });

            modelBuilder.Entity("gb_active_service_api.Models.Responsible", b =>
                {
                    b.Navigation("Actives");
                });
#pragma warning restore 612, 618
        }
    }
}
